
version: "3"

services:
  web:
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    links:
        - mongodb
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="nest"
    ports:
      - 27017:27017